name: enduro_diagnostics_map
description: "Enduro Service Diagnostics Map"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  firebase_core: 3.6.0
  get_it: 8.0.2
  equatable: 2.0.5
  flutter_bloc: 8.1.6
  pdf: 3.11.1
  flutter_pdfview: 1.3.4
  path_provider: 2.1.5
  printing: 5.13.4
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_gen:
  # settings
  output: lib/gen/
  line_length: 100
  # assets
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
  fonts:
    enabled: false

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
