name: enduro_diagnostics_map
description: "Enduro Service Diagnostics Map"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  get_it: 8.0.2
  equatable: 2.0.5
  flutter_bloc: 8.1.6
  pdf: 3.11.1
  flutter_pdfview: 1.3.4
  path_provider: 2.1.5
  printing: 5.13.4
  intl: 0.19.0
  share_plus: 10.1.2
  flutter_native_splash: 2.4.2

  firebase_core: 3.7.0
  firebase_remote_config: 5.1.4
  cloud_firestore: 5.4.5
  flutter_dotenv: 5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  flutter_launcher_icons: 0.14.1

flutter_gen:
  # settings
  output: lib/gen/
  line_length: 100
  # assets
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: false
  fonts:
    enabled: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_native_splash:
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove
  color: "#2C2C2C"
  image: assets/splash.png
  color_dark: "#2C2C2C"
  image_dark: assets/splash.png
  android_12:
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/android12splash.png
    color: "#2C2C2C"
    image_dark: assets/android12splash.png
    color_dark: "#2C2C2C"

flutter_launcher_icons:
  image_path: "assets/icon/icon_ios_2.png"
  android: "launcher_icon"
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true

